export const QUERY_KEYS = {
  ME: "ME",
  WORKOUTS: "WORKOUTS",
  FOOD_LOGS: "FOOD_LOGS",
  NUTRITION_ANALYTICS: "NUTRITION_ANALYTICS",
  WORKOUT_ANALYTICS: "WORKOUT_ANALYTICS",
  AI_MESSAGES: "AI_MESSAGES",
};
